version: '3'
services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount workspace folder to container's /workspace
      - ..:/workspace:cached
    # Keep container running with sleep infinity command
    command: sleep infinity
    ports:
      - "5555:5000"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
